### ISSUE TITLE
Changes references to myst2canvas to md2canvas

### ISSUE THREAD

**Issue by firasm** [hcolclou/md2canvas#3]
Hi @hcolclou !

Thanks for this, I'll be going through the examples and trying to setup a workflow for my TAs. I have noticed a few instances of myst2canvas scattered about, mind if I send a PR to change those?

**Comment by hcolclou** [comment]
Please do :) there will be another, smaller, example going up soon too!

**Comment by hcolclou** [comment]
Please let me know if you come across any issues or if anything is unclear at all! As far as I know you are the first user who isn't me

**Comment by hcolclou** [comment]
Pull request pulled!
